### ISSUE TITLE
Add support to persist rich text editor layout

### ISSUE THREAD

**Issue by benji300** [benji300/joplin-persistent-layout#4]
Add support to also persist the richt text editor layout with a new special tag: 
```
layout:richtext | rtf | wysiwyg | ?
```

The name of the tag is still to be defined...

**Comment by msbentley** [comment]
I was just going to ask about this :) I have imported thousands of notes from Evernote in html format, but want to write new notes in the MD editor going forward, so having a way to tag all of imported notes in the rich text editor, and new ones in the Markdown edit would be amazing!
